/**
 * CWMS Data API
 * CWMS REST API for Data Retrieval
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.cwmsjs);
  }
}(this, function(expect, cwmsjs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new cwmsjs.LocationGroup();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LocationGroup', function() {
    it('should create an instance of LocationGroup', function() {
      // uncomment below and update the code to test LocationGroup
      //var instance = new cwmsjs.LocationGroup();
      //expect(instance).to.be.a(cwmsjs.LocationGroup);
    });

    it('should have the property officeId (base name: "office-id")', function() {
      // uncomment below and update the code to test the property officeId
      //var instance = new cwmsjs.LocationGroup();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new cwmsjs.LocationGroup();
      //expect(instance).to.be();
    });

    it('should have the property locationCategory (base name: "location-category")', function() {
      // uncomment below and update the code to test the property locationCategory
      //var instance = new cwmsjs.LocationGroup();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new cwmsjs.LocationGroup();
      //expect(instance).to.be();
    });

    it('should have the property sharedLocAliasId (base name: "shared-loc-alias-id")', function() {
      // uncomment below and update the code to test the property sharedLocAliasId
      //var instance = new cwmsjs.LocationGroup();
      //expect(instance).to.be();
    });

    it('should have the property sharedRefLocationId (base name: "shared-ref-location-id")', function() {
      // uncomment below and update the code to test the property sharedRefLocationId
      //var instance = new cwmsjs.LocationGroup();
      //expect(instance).to.be();
    });

    it('should have the property locGroupAttribute (base name: "loc-group-attribute")', function() {
      // uncomment below and update the code to test the property locGroupAttribute
      //var instance = new cwmsjs.LocationGroup();
      //expect(instance).to.be();
    });

    it('should have the property assignedLocations (base name: "assigned-locations")', function() {
      // uncomment below and update the code to test the property assignedLocations
      //var instance = new cwmsjs.LocationGroup();
      //expect(instance).to.be();
    });

  });

}));
