/**
 * CWMS Data API
 * CWMS REST API for Data Retrieval
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.cwmsjs);
  }
}(this, function(expect, cwmsjs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new cwmsjs.TransitionalRating();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TransitionalRating', function() {
    it('should create an instance of TransitionalRating', function() {
      // uncomment below and update the code to test TransitionalRating
      //var instance = new cwmsjs.TransitionalRating();
      //expect(instance).to.be.a(cwmsjs.TransitionalRating);
    });

    it('should have the property sourceRatings (base name: "source-ratings")', function() {
      // uncomment below and update the code to test the property sourceRatings
      //var instance = new cwmsjs.TransitionalRating();
      //expect(instance).to.be();
    });

    it('should have the property conditions (base name: "conditions")', function() {
      // uncomment below and update the code to test the property conditions
      //var instance = new cwmsjs.TransitionalRating();
      //expect(instance).to.be();
    });

    it('should have the property evaluations (base name: "evaluations")', function() {
      // uncomment below and update the code to test the property evaluations
      //var instance = new cwmsjs.TransitionalRating();
      //expect(instance).to.be();
    });

  });

}));
