/*
 * CWMS Radar
 * CWMS REST API for Data Retrieval
 *
 * The version of the OpenAPI document: 2.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for StreamReach
 */
public class StreamReachTest {
    private final StreamReach model = new StreamReach();

    /**
     * Model tests for StreamReach
     */
    @Test
    public void testStreamReach() {
        // TODO: test StreamReach
    }

    /**
     * Test the property 'upstreamLocationName'
     */
    @Test
    public void upstreamLocationNameTest() {
        // TODO: test upstreamLocationName
    }

    /**
     * Test the property 'downstreamLocationName'
     */
    @Test
    public void downstreamLocationNameTest() {
        // TODO: test downstreamLocationName
    }

    /**
     * Test the property 'streamName'
     */
    @Test
    public void streamNameTest() {
        // TODO: test streamName
    }

    /**
     * Test the property 'reachName'
     */
    @Test
    public void reachNameTest() {
        // TODO: test reachName
    }

    /**
     * Test the property 'officeId'
     */
    @Test
    public void officeIdTest() {
        // TODO: test officeId
    }

    /**
     * Test the property 'comment'
     */
    @Test
    public void commentTest() {
        // TODO: test comment
    }

    /**
     * Test the property '_configuration'
     */
    @Test
    public void _configurationTest() {
        // TODO: test _configuration
    }

}
