/*
 * CWMS Radar
 * CWMS REST API for Data Retrieval
 *
 * The version of the OpenAPI document: 2.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets DatabaseLoadMethod
 */
@JsonAdapter(DatabaseLoadMethod.Adapter.class)
public enum DatabaseLoadMethod {
  
  EAGER("EAGER"),
  
  LAZY("LAZY"),
  
  REFERENCE("REFERENCE");

  private String value;

  DatabaseLoadMethod(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static DatabaseLoadMethod fromValue(String value) {
    for (DatabaseLoadMethod b : DatabaseLoadMethod.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<DatabaseLoadMethod> {
    @Override
    public void write(final JsonWriter jsonWriter, final DatabaseLoadMethod enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public DatabaseLoadMethod read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return DatabaseLoadMethod.fromValue(value);
    }
  }
}

