/**
 * CWMS Radar
 * CWMS REST API for Data Retrieval
 *
 * The version of the OpenAPI document: 2.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AbstractRatingMetadata from './AbstractRatingMetadata';
import TransitionalRatingAllOf from './TransitionalRatingAllOf';

/**
 * The TransitionalRating model module.
 * @module model/TransitionalRating
 * @version 2.5
 */
class TransitionalRating {
    /**
     * Constructs a new <code>TransitionalRating</code>.
     * @alias module:model/TransitionalRating
     * @extends module:model/AbstractRatingMetadata
     * @implements module:model/AbstractRatingMetadata
     * @implements module:model/TransitionalRatingAllOf
     */
    constructor() { 
        AbstractRatingMetadata.initialize(this);TransitionalRatingAllOf.initialize(this);
        TransitionalRating.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TransitionalRating</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TransitionalRating} obj Optional instance to populate.
     * @return {module:model/TransitionalRating} The populated <code>TransitionalRating</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TransitionalRating();
            AbstractRatingMetadata.constructFromObject(data, obj);
            AbstractRatingMetadata.constructFromObject(data, obj);
            TransitionalRatingAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('source-ratings')) {
                obj['source-ratings'] = ApiClient.convertToType(data['source-ratings'], ['String']);
            }
            if (data.hasOwnProperty('conditions')) {
                obj['conditions'] = ApiClient.convertToType(data['conditions'], ['String']);
            }
            if (data.hasOwnProperty('evaluations')) {
                obj['evaluations'] = ApiClient.convertToType(data['evaluations'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TransitionalRating</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TransitionalRating</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['source-ratings'])) {
            throw new Error("Expected the field `source-ratings` to be an array in the JSON data but got " + data['source-ratings']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['conditions'])) {
            throw new Error("Expected the field `conditions` to be an array in the JSON data but got " + data['conditions']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['evaluations'])) {
            throw new Error("Expected the field `evaluations` to be an array in the JSON data but got " + data['evaluations']);
        }

        return true;
    }


}



/**
 * @member {Array.<String>} source-ratings
 */
TransitionalRating.prototype['source-ratings'] = undefined;

/**
 * @member {Array.<String>} conditions
 */
TransitionalRating.prototype['conditions'] = undefined;

/**
 * @member {Array.<String>} evaluations
 */
TransitionalRating.prototype['evaluations'] = undefined;


// Implement AbstractRatingMetadata interface:
/**
 * @member {Array.<Object>} source-ratings
 */
AbstractRatingMetadata.prototype['source-ratings'] = undefined;
/**
 * @member {Array.<String>} conditions
 */
AbstractRatingMetadata.prototype['conditions'] = undefined;
/**
 * @member {Array.<String>} evaluations
 */
AbstractRatingMetadata.prototype['evaluations'] = undefined;
/**
 * @member {String} connections
 */
AbstractRatingMetadata.prototype['connections'] = undefined;
/**
 * @member {String} expression
 */
AbstractRatingMetadata.prototype['expression'] = undefined;
/**
 * @member {String} in-range-method
 */
AbstractRatingMetadata.prototype['in-range-method'] = undefined;
/**
 * @member {String} out-range-low-method
 */
AbstractRatingMetadata.prototype['out-range-low-method'] = undefined;
/**
 * @member {String} out-range-high-method
 */
AbstractRatingMetadata.prototype['out-range-high-method'] = undefined;
// Implement TransitionalRatingAllOf interface:
/**
 * @member {Array.<String>} source-ratings
 */
TransitionalRatingAllOf.prototype['source-ratings'] = undefined;
/**
 * @member {Array.<String>} conditions
 */
TransitionalRatingAllOf.prototype['conditions'] = undefined;
/**
 * @member {Array.<String>} evaluations
 */
TransitionalRatingAllOf.prototype['evaluations'] = undefined;




export default TransitionalRating;

