/**
 * CWMS Data API
 * CWMS REST API for Data Retrieval
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CwmsDataApi);
  }
}(this, function(expect, CwmsDataApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CwmsDataApi.TimeSeriesIdentifierApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TimeSeriesIdentifierApi', function() {
    describe('deleteCwmsDataTimeseriesIdentifierDescriptorWithTimeseriesId', function() {
      it('should call deleteCwmsDataTimeseriesIdentifierDescriptorWithTimeseriesId successfully', function(done) {
        //uncomment below and update the code to test deleteCwmsDataTimeseriesIdentifierDescriptorWithTimeseriesId
        //instance.deleteCwmsDataTimeseriesIdentifierDescriptorWithTimeseriesId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCwmsDataTimeseriesIdentifierDescriptor', function() {
      it('should call getCwmsDataTimeseriesIdentifierDescriptor successfully', function(done) {
        //uncomment below and update the code to test getCwmsDataTimeseriesIdentifierDescriptor
        //instance.getCwmsDataTimeseriesIdentifierDescriptor(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCwmsDataTimeseriesIdentifierDescriptorWithTimeseriesId', function() {
      it('should call getCwmsDataTimeseriesIdentifierDescriptorWithTimeseriesId successfully', function(done) {
        //uncomment below and update the code to test getCwmsDataTimeseriesIdentifierDescriptorWithTimeseriesId
        //instance.getCwmsDataTimeseriesIdentifierDescriptorWithTimeseriesId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('patchCwmsDataTimeseriesIdentifierDescriptorWithTimeseriesId', function() {
      it('should call patchCwmsDataTimeseriesIdentifierDescriptorWithTimeseriesId successfully', function(done) {
        //uncomment below and update the code to test patchCwmsDataTimeseriesIdentifierDescriptorWithTimeseriesId
        //instance.patchCwmsDataTimeseriesIdentifierDescriptorWithTimeseriesId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postCwmsDataTimeseriesIdentifierDescriptor', function() {
      it('should call postCwmsDataTimeseriesIdentifierDescriptor successfully', function(done) {
        //uncomment below and update the code to test postCwmsDataTimeseriesIdentifierDescriptor
        //instance.postCwmsDataTimeseriesIdentifierDescriptor(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
