/* tslint:disable */
/* eslint-disable */
/**
 * CWMS Data API
 * CWMS REST API for Data Retrieval
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CdaError,
  Parameter,
} from '../models/index';
import {
    CdaErrorFromJSON,
    CdaErrorToJSON,
    ParameterFromJSON,
    ParameterToJSON,
} from '../models/index';

export interface GetParametersRequest {
    format?: string;
    office?: string;
}

/**
 * 
 */
export class ParametersApi extends runtime.BaseAPI {

    /**
     * Get CwmsData parameters
     */
    async getParametersRaw(requestParameters: GetParametersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Parameter>>> {
        const queryParameters: any = {};

        if (requestParameters['format'] != null) {
            queryParameters['format'] = requestParameters['format'];
        }

        if (requestParameters['office'] != null) {
            queryParameters['office'] = requestParameters['office'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKey authentication
        }

        const response = await this.request({
            path: `/parameters`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ParameterFromJSON));
    }

    /**
     * Get CwmsData parameters
     */
    async getParameters(requestParameters: GetParametersRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Parameter>> {
        const response = await this.getParametersRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
