/**
 * CWMS Data API
 * CWMS REST API for Data Retrieval
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AssignedTimeSeries from './AssignedTimeSeries';
import TimeSeriesCategory from './TimeSeriesCategory';

/**
 * The TimeSeriesGroup model module.
 * @module model/TimeSeriesGroup
 * @version 1.4.0
 */
class TimeSeriesGroup {
    /**
     * Constructs a new <code>TimeSeriesGroup</code>.
     * A representation of a timeseries group
     * @alias module:model/TimeSeriesGroup
     * @param officeId {String} Owning office of object.
     */
    constructor(officeId) { 
        
        TimeSeriesGroup.initialize(this, officeId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, officeId) { 
        obj['office-id'] = officeId;
    }

    /**
     * Constructs a <code>TimeSeriesGroup</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TimeSeriesGroup} obj Optional instance to populate.
     * @return {module:model/TimeSeriesGroup} The populated <code>TimeSeriesGroup</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TimeSeriesGroup();

            if (data.hasOwnProperty('office-id')) {
                obj['office-id'] = ApiClient.convertToType(data['office-id'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('time-series-category')) {
                obj['time-series-category'] = TimeSeriesCategory.constructFromObject(data['time-series-category']);
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('shared-alias-id')) {
                obj['shared-alias-id'] = ApiClient.convertToType(data['shared-alias-id'], 'String');
            }
            if (data.hasOwnProperty('shared-ref-ts-id')) {
                obj['shared-ref-ts-id'] = ApiClient.convertToType(data['shared-ref-ts-id'], 'String');
            }
            if (data.hasOwnProperty('assigned-time-series')) {
                obj['assigned-time-series'] = ApiClient.convertToType(data['assigned-time-series'], [AssignedTimeSeries]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TimeSeriesGroup</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TimeSeriesGroup</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TimeSeriesGroup.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['office-id'] && !(typeof data['office-id'] === 'string' || data['office-id'] instanceof String)) {
            throw new Error("Expected the field `office-id` to be a primitive type in the JSON string but got " + data['office-id']);
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // validate the optional field `time-series-category`
        if (data['time-series-category']) { // data not null
          TimeSeriesCategory.validateJSON(data['time-series-category']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['shared-alias-id'] && !(typeof data['shared-alias-id'] === 'string' || data['shared-alias-id'] instanceof String)) {
            throw new Error("Expected the field `shared-alias-id` to be a primitive type in the JSON string but got " + data['shared-alias-id']);
        }
        // ensure the json data is a string
        if (data['shared-ref-ts-id'] && !(typeof data['shared-ref-ts-id'] === 'string' || data['shared-ref-ts-id'] instanceof String)) {
            throw new Error("Expected the field `shared-ref-ts-id` to be a primitive type in the JSON string but got " + data['shared-ref-ts-id']);
        }
        if (data['assigned-time-series']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['assigned-time-series'])) {
                throw new Error("Expected the field `assigned-time-series` to be an array in the JSON data but got " + data['assigned-time-series']);
            }
            // validate the optional field `assigned-time-series` (array)
            for (const item of data['assigned-time-series']) {
                AssignedTimeSeries.validateJSON(item);
            };
        }

        return true;
    }


}

TimeSeriesGroup.RequiredProperties = ["office-id"];

/**
 * Owning office of object.
 * @member {String} office-id
 */
TimeSeriesGroup.prototype['office-id'] = undefined;

/**
 * @member {String} id
 */
TimeSeriesGroup.prototype['id'] = undefined;

/**
 * @member {module:model/TimeSeriesCategory} time-series-category
 */
TimeSeriesGroup.prototype['time-series-category'] = undefined;

/**
 * @member {String} description
 */
TimeSeriesGroup.prototype['description'] = undefined;

/**
 * @member {String} shared-alias-id
 */
TimeSeriesGroup.prototype['shared-alias-id'] = undefined;

/**
 * @member {String} shared-ref-ts-id
 */
TimeSeriesGroup.prototype['shared-ref-ts-id'] = undefined;

/**
 * @member {Array.<module:model/AssignedTimeSeries>} assigned-time-series
 */
TimeSeriesGroup.prototype['assigned-time-series'] = undefined;






export default TimeSeriesGroup;

