/**
 * CWMS Data API
 * CWMS REST API for Data Retrieval
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class UnitSystem.
* @enum {}
* @readonly
*/
export default class UnitSystem {
    
        /**
         * value: "SI"
         * @const
         */
        "SI" = "SI";

    
        /**
         * value: "EN"
         * @const
         */
        "EN" = "EN";

    

    /**
    * Returns a <code>UnitSystem</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/UnitSystem} The enum <code>UnitSystem</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

