/**
 * CWMS Radar
 * CWMS REST API for Data Retrieval
 *
 * The version of the OpenAPI document: 2.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CwmsRadar);
  }
}(this, function(expect, CwmsRadar) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CwmsRadar.AssignedTimeSeries();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AssignedTimeSeries', function() {
    it('should create an instance of AssignedTimeSeries', function() {
      // uncomment below and update the code to test AssignedTimeSeries
      //var instance = new CwmsRadar.AssignedTimeSeries();
      //expect(instance).to.be.a(CwmsRadar.AssignedTimeSeries);
    });

    it('should have the property timeseriesId (base name: "timeseriesId")', function() {
      // uncomment below and update the code to test the property timeseriesId
      //var instance = new CwmsRadar.AssignedTimeSeries();
      //expect(instance).to.be();
    });

    it('should have the property tsCode (base name: "tsCode")', function() {
      // uncomment below and update the code to test the property tsCode
      //var instance = new CwmsRadar.AssignedTimeSeries();
      //expect(instance).to.be();
    });

    it('should have the property aliasId (base name: "aliasId")', function() {
      // uncomment below and update the code to test the property aliasId
      //var instance = new CwmsRadar.AssignedTimeSeries();
      //expect(instance).to.be();
    });

    it('should have the property refTsId (base name: "refTsId")', function() {
      // uncomment below and update the code to test the property refTsId
      //var instance = new CwmsRadar.AssignedTimeSeries();
      //expect(instance).to.be();
    });

    it('should have the property attribute (base name: "attribute")', function() {
      // uncomment below and update the code to test the property attribute
      //var instance = new CwmsRadar.AssignedTimeSeries();
      //expect(instance).to.be();
    });

  });

}));
