/*
 * CWMS Radar
 * CWMS REST API for Data Retrieval
 *
 * The version of the OpenAPI document: 2.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Clob;
import org.openapitools.client.model.Clobs;
import org.openapitools.client.model.RadarError;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ClobApi
 */
@Disabled
public class ClobApiTest {

    private final ClobApi api = new ClobApi();

    /**
     * Get cwmsData clobs
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCwmsDataClobsTest() throws ApiException {
        String office = null;
        String page = null;
        String cursor = null;
        Integer pageSize = null;
        Integer pageSize2 = null;
        Boolean includeValues = null;
        Boolean includeValues2 = null;
        String like = null;
        Clobs response = api.getCwmsDataClobs(office, page, cursor, pageSize, pageSize2, includeValues, includeValues2, like);
        // TODO: test validations
    }

    /**
     * Get cwmsData clobs with clobId
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCwmsDataClobsWithClobIdTest() throws ApiException {
        String clobId = null;
        String office = null;
        Clob response = api.getCwmsDataClobsWithClobId(clobId, office);
        // TODO: test validations
    }

}
