/**
 * CWMS Radar
 * CWMS REST API for Data Retrieval
 *
 * The version of the OpenAPI document: 2.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Basin from '../model/Basin';
import RadarError from '../model/RadarError';

/**
* BasinsBeta service.
* @module api/BasinsBetaApi
* @version 2.5
*/
export default class BasinsBetaApi {

    /**
    * Constructs a new BasinsBetaApi. 
    * @alias module:api/BasinsBetaApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getCwmsDataBasins operation.
     * @callback module:api/BasinsBetaApi~getCwmsDataBasinsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Basin} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get cwmsData basins
     * Returns CWMS Basin Data
     * @param {Object} opts Optional parameters
     * @param {String} [office] Specifies the owning office of the basin whose data is to be included in the response. If this field is not specified, matching basin information from all offices shall be returned.
     * @param {String} [unit] Specifies the unit or unit system of the response. Valid values for the unit field are:   1. EN.   Specifies English unit system. Basin values will be in the default English units for their parameters. (This is default if no value is entered)  2. SI.   Specifies the SI unit system. Basin values will be in the default SI units for their parameters.
     * @param {module:api/BasinsBetaApi~getCwmsDataBasinsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Basin}
     */
    getCwmsDataBasins(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'office': opts['office'],
        'unit': opts['unit']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json', 'application/vnd.named+pg+json'];
      let returnType = Basin;
      return this.apiClient.callApi(
        '/cwms-data/basins', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getCwmsDataBasinsWithBasinId operation.
     * @callback module:api/BasinsBetaApi~getCwmsDataBasinsWithBasinIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Basin} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get cwmsData basins with basinId
     * Returns CWMS Basin Data
     * @param {String} basinId 
     * @param {Object} opts Optional parameters
     * @param {String} [office] Specifies the owning office of the basin whose data is to be included in the response. If this field is not specified, matching basin information from all offices shall be returned.
     * @param {String} [unit] Specifies the unit or unit system of the response. Valid values for the unit field are:   1. EN.   Specifies English unit system. Basin values will be in the default English units for their parameters. (This is default if no value is entered)  2. SI.   Specifies the SI unit system. Basin values will be in the default SI units for their parameters.
     * @param {module:api/BasinsBetaApi~getCwmsDataBasinsWithBasinIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Basin}
     */
    getCwmsDataBasinsWithBasinId(basinId, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'basinId' is set
      if (basinId === undefined || basinId === null) {
        throw new Error("Missing the required parameter 'basinId' when calling getCwmsDataBasinsWithBasinId");
      }

      let pathParams = {
        'basin-id': basinId
      };
      let queryParams = {
        'office': opts['office'],
        'unit': opts['unit']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json', 'application/vnd.named+pg+json'];
      let returnType = Basin;
      return this.apiClient.callApi(
        '/cwms-data/basins/{basin-id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
