/**
 * CWMS Radar
 * CWMS REST API for Data Retrieval
 *
 * The version of the OpenAPI document: 2.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import RadarError from '../model/RadarError';
import SpecifiedLevel from '../model/SpecifiedLevel';

/**
* SpecifiedLevels service.
* @module api/SpecifiedLevelsApi
* @version 2.5
*/
export default class SpecifiedLevelsApi {

    /**
    * Constructs a new SpecifiedLevelsApi. 
    * @alias module:api/SpecifiedLevelsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getCwmsDataSpecifiedLevels operation.
     * @callback module:api/SpecifiedLevelsApi~getCwmsDataSpecifiedLevelsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SpecifiedLevel} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get cwmsData specifiedLevels
     * @param {Object} opts Optional parameters
     * @param {String} [office] Specifies the owning office of the Specified Levels whose data is to be included in the response. If this field is not specified, matching rating information from all offices shall be returned.
     * @param {String} [templateIdMask] Mask that specifies the IDs to be included in the response. If this field is not specified, all specified levels shall be returned.
     * @param {module:api/SpecifiedLevelsApi~getCwmsDataSpecifiedLevelsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SpecifiedLevel}
     */
    getCwmsDataSpecifiedLevels(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'office': opts['office'],
        'template-id-mask': opts['templateIdMask']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json', 'application/json;version=2'];
      let returnType = SpecifiedLevel;
      return this.apiClient.callApi(
        '/cwms-data/specified-levels', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
