/* tslint:disable */
/* eslint-disable */
/**
 * CWMS Data API
 * CWMS REST API for Data Retrieval
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CwmsId
 */
export interface CwmsId {
    /**
     * 
     * @type {string}
     * @memberof CwmsId
     */
    officeId?: string;
    /**
     * 
     * @type {string}
     * @memberof CwmsId
     */
    name?: string;
}

/**
 * Check if a given object implements the CwmsId interface.
 */
export function instanceOfCwmsId(value: object): boolean {
    return true;
}

export function CwmsIdFromJSON(json: any): CwmsId {
    return CwmsIdFromJSONTyped(json, false);
}

export function CwmsIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): CwmsId {
    if (json == null) {
        return json;
    }
    return {
        
        'officeId': json['office-id'] == null ? undefined : json['office-id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function CwmsIdToJSON(value?: CwmsId | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'office-id': value['officeId'],
        'name': value['name'],
    };
}

