/* tslint:disable */
/* eslint-disable */
/**
 * CWMS Data API
 * CWMS REST API for Data Retrieval
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Property
 */
export interface Property {
    /**
     * Owning office of object.
     * @type {string}
     * @memberof Property
     */
    officeId: string;
    /**
     * 
     * @type {string}
     * @memberof Property
     */
    category: string;
    /**
     * 
     * @type {string}
     * @memberof Property
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Property
     */
    value?: string;
    /**
     * 
     * @type {string}
     * @memberof Property
     */
    comment?: string;
}

/**
 * Check if a given object implements the Property interface.
 */
export function instanceOfProperty(value: object): boolean {
    if (!('officeId' in value)) return false;
    if (!('category' in value)) return false;
    if (!('name' in value)) return false;
    return true;
}

export function PropertyFromJSON(json: any): Property {
    return PropertyFromJSONTyped(json, false);
}

export function PropertyFromJSONTyped(json: any, ignoreDiscriminator: boolean): Property {
    if (json == null) {
        return json;
    }
    return {
        
        'officeId': json['office-id'],
        'category': json['category'],
        'name': json['name'],
        'value': json['value'] == null ? undefined : json['value'],
        'comment': json['comment'] == null ? undefined : json['comment'],
    };
}

export function PropertyToJSON(value?: Property | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'office-id': value['officeId'],
        'category': value['category'],
        'name': value['name'],
        'value': value['value'],
        'comment': value['comment'],
    };
}

