/* tslint:disable */
/* eslint-disable */
/**
 * CWMS Data API
 * CWMS REST API for Data Retrieval
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BaseRatingMetadata } from './BaseRatingMetadata';
import {
    BaseRatingMetadataFromJSON,
    BaseRatingMetadataFromJSONTyped,
    BaseRatingMetadataToJSON,
} from './BaseRatingMetadata';
import type { RatingSpec } from './RatingSpec';
import {
    RatingSpecFromJSON,
    RatingSpecFromJSONTyped,
    RatingSpecToJSON,
} from './RatingSpec';

/**
 * 
 * @export
 * @interface RatingMetadata
 */
export interface RatingMetadata {
    /**
     * 
     * @type {RatingSpec}
     * @memberof RatingMetadata
     */
    ratingSpec?: RatingSpec;
    /**
     * 
     * @type {Array<BaseRatingMetadata>}
     * @memberof RatingMetadata
     */
    ratings?: Array<BaseRatingMetadata>;
}

/**
 * Check if a given object implements the RatingMetadata interface.
 */
export function instanceOfRatingMetadata(value: object): boolean {
    return true;
}

export function RatingMetadataFromJSON(json: any): RatingMetadata {
    return RatingMetadataFromJSONTyped(json, false);
}

export function RatingMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): RatingMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'ratingSpec': json['rating-spec'] == null ? undefined : RatingSpecFromJSON(json['rating-spec']),
        'ratings': json['ratings'] == null ? undefined : ((json['ratings'] as Array<any>).map(BaseRatingMetadataFromJSON)),
    };
}

export function RatingMetadataToJSON(value?: RatingMetadata | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'rating-spec': RatingSpecToJSON(value['ratingSpec']),
        'ratings': value['ratings'] == null ? undefined : ((value['ratings'] as Array<any>).map(BaseRatingMetadataToJSON)),
    };
}

