/* tslint:disable */
/* eslint-disable */
/**
 * CWMS Data API
 * CWMS REST API for Data Retrieval
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StandardTextId
 */
export interface StandardTextId {
    /**
     * Owning office of object.
     * @type {string}
     * @memberof StandardTextId
     */
    officeId: string;
    /**
     * 
     * @type {string}
     * @memberof StandardTextId
     */
    id?: string;
}

/**
 * Check if a given object implements the StandardTextId interface.
 */
export function instanceOfStandardTextId(value: object): boolean {
    if (!('officeId' in value)) return false;
    return true;
}

export function StandardTextIdFromJSON(json: any): StandardTextId {
    return StandardTextIdFromJSONTyped(json, false);
}

export function StandardTextIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): StandardTextId {
    if (json == null) {
        return json;
    }
    return {
        
        'officeId': json['office-id'],
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function StandardTextIdToJSON(value?: StandardTextId | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'office-id': value['officeId'],
        'id': value['id'],
    };
}

