/* tslint:disable */
/* eslint-disable */
/**
 * CWMS Data API
 * CWMS REST API for Data Retrieval
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TimeSeriesIdentifierDescriptor } from './TimeSeriesIdentifierDescriptor';
import {
    TimeSeriesIdentifierDescriptorFromJSON,
    TimeSeriesIdentifierDescriptorFromJSONTyped,
    TimeSeriesIdentifierDescriptorToJSON,
} from './TimeSeriesIdentifierDescriptor';

/**
 * 
 * @export
 * @interface TimeSeriesIdentifierDescriptors
 */
export interface TimeSeriesIdentifierDescriptors {
    /**
     * 
     * @type {Array<TimeSeriesIdentifierDescriptor>}
     * @memberof TimeSeriesIdentifierDescriptors
     */
    descriptors?: Array<TimeSeriesIdentifierDescriptor>;
    /**
     * The cursor to the next page of data; null if there is no more data
     * @type {string}
     * @memberof TimeSeriesIdentifierDescriptors
     */
    readonly nextPage?: string;
    /**
     * The cursor to the current page of data
     * @type {string}
     * @memberof TimeSeriesIdentifierDescriptors
     */
    readonly page?: string;
    /**
     * The number of records fetched per-page; this may be larger than the number of records actually retrieved
     * @type {number}
     * @memberof TimeSeriesIdentifierDescriptors
     */
    readonly pageSize?: number;
    /**
     * The total number of records retrieved; null or not present if not supported or unknown
     * @type {number}
     * @memberof TimeSeriesIdentifierDescriptors
     */
    readonly total?: number;
}

/**
 * Check if a given object implements the TimeSeriesIdentifierDescriptors interface.
 */
export function instanceOfTimeSeriesIdentifierDescriptors(value: object): boolean {
    return true;
}

export function TimeSeriesIdentifierDescriptorsFromJSON(json: any): TimeSeriesIdentifierDescriptors {
    return TimeSeriesIdentifierDescriptorsFromJSONTyped(json, false);
}

export function TimeSeriesIdentifierDescriptorsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeSeriesIdentifierDescriptors {
    if (json == null) {
        return json;
    }
    return {
        
        'descriptors': json['descriptors'] == null ? undefined : ((json['descriptors'] as Array<any>).map(TimeSeriesIdentifierDescriptorFromJSON)),
        'nextPage': json['next-page'] == null ? undefined : json['next-page'],
        'page': json['page'] == null ? undefined : json['page'],
        'pageSize': json['page-size'] == null ? undefined : json['page-size'],
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function TimeSeriesIdentifierDescriptorsToJSON(value?: TimeSeriesIdentifierDescriptors | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'descriptors': value['descriptors'] == null ? undefined : ((value['descriptors'] as Array<any>).map(TimeSeriesIdentifierDescriptorToJSON)),
    };
}

