/* tslint:disable */
/* eslint-disable */
/**
 * CWMS Data API
 * CWMS REST API for Data Retrieval
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TimeseriesIntervalUnitsInnerDuration
 */
export interface TimeseriesIntervalUnitsInnerDuration {
    /**
     * 
     * @type {number}
     * @memberof TimeseriesIntervalUnitsInnerDuration
     */
    seconds?: number;
    /**
     * 
     * @type {number}
     * @memberof TimeseriesIntervalUnitsInnerDuration
     */
    nano?: number;
    /**
     * 
     * @type {boolean}
     * @memberof TimeseriesIntervalUnitsInnerDuration
     */
    zero?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TimeseriesIntervalUnitsInnerDuration
     */
    negative?: boolean;
}

/**
 * Check if a given object implements the TimeseriesIntervalUnitsInnerDuration interface.
 */
export function instanceOfTimeseriesIntervalUnitsInnerDuration(value: object): boolean {
    return true;
}

export function TimeseriesIntervalUnitsInnerDurationFromJSON(json: any): TimeseriesIntervalUnitsInnerDuration {
    return TimeseriesIntervalUnitsInnerDurationFromJSONTyped(json, false);
}

export function TimeseriesIntervalUnitsInnerDurationFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeseriesIntervalUnitsInnerDuration {
    if (json == null) {
        return json;
    }
    return {
        
        'seconds': json['seconds'] == null ? undefined : json['seconds'],
        'nano': json['nano'] == null ? undefined : json['nano'],
        'zero': json['zero'] == null ? undefined : json['zero'],
        'negative': json['negative'] == null ? undefined : json['negative'],
    };
}

export function TimeseriesIntervalUnitsInnerDurationToJSON(value?: TimeseriesIntervalUnitsInnerDuration | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'seconds': value['seconds'],
        'nano': value['nano'],
        'zero': value['zero'],
        'negative': value['negative'],
    };
}

