/**
 * CWMS Data API
 * CWMS REST API for Data Retrieval
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Stream } from '../models/Stream';
import { HttpFile } from '../http/http';

export class Basin {
    /**
    * Owning office of object.
    */
    'officeId': string;
    'basinName'?: string;
    'primaryStream'?: Stream;
    'sortOrder'?: number;
    'basinArea'?: number;
    'contributingArea'?: number;
    'parentBasinId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "officeId",
            "baseName": "office-id",
            "type": "string",
            "format": ""
        },
        {
            "name": "basinName",
            "baseName": "basin-name",
            "type": "string",
            "format": ""
        },
        {
            "name": "primaryStream",
            "baseName": "primary-stream",
            "type": "Stream",
            "format": ""
        },
        {
            "name": "sortOrder",
            "baseName": "sort-order",
            "type": "number",
            "format": "double"
        },
        {
            "name": "basinArea",
            "baseName": "basin-area",
            "type": "number",
            "format": "double"
        },
        {
            "name": "contributingArea",
            "baseName": "contributing-area",
            "type": "number",
            "format": "double"
        },
        {
            "name": "parentBasinId",
            "baseName": "parent-basin-id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Basin.attributeTypeMap;
    }

    public constructor() {
    }
}

