"use strict";
/**
 * CWMS Data API
 * CWMS REST API for Data Retrieval
 *
 * OpenAPI spec version: 3.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CatalogableEndpoint = void 0;
/**
* Set of data for which a larger catalog can be built.
*/
var CatalogableEndpoint;
(function (CatalogableEndpoint) {
    CatalogableEndpoint["Timeseries"] = "TIMESERIES";
    CatalogableEndpoint["Locations"] = "LOCATIONS";
})(CatalogableEndpoint || (exports.CatalogableEndpoint = CatalogableEndpoint = {}));
