/**
 * CWMS Radar
 * CWMS REST API for Data Retrieval
 *
 * OpenAPI spec version: 2.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class AssignedTimeSeries {
    'timeseriesId'?: string;
    'tsCode'?: number;
    'aliasId'?: string;
    'refTsId'?: string;
    'attribute'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "timeseriesId",
            "baseName": "timeseriesId",
            "type": "string",
            "format": ""
        },
        {
            "name": "tsCode",
            "baseName": "tsCode",
            "type": "number",
            "format": ""
        },
        {
            "name": "aliasId",
            "baseName": "aliasId",
            "type": "string",
            "format": ""
        },
        {
            "name": "refTsId",
            "baseName": "refTsId",
            "type": "string",
            "format": ""
        },
        {
            "name": "attribute",
            "baseName": "attribute",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return AssignedTimeSeries.attributeTypeMap;
    }

    public constructor() {
    }
}

