/**
 * CWMS Radar
 * CWMS REST API for Data Retrieval
 *
 * OpenAPI spec version: 2.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Offset } from '../models/Offset';
import { HttpFile } from '../http/http';

export class VerticalDatumInfo {
    'office'?: string;
    'unit'?: string;
    'location'?: string;
    'nativeDatum'?: string;
    'elevation'?: number;
    'offsets'?: Array<Offset>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "office",
            "baseName": "office",
            "type": "string",
            "format": ""
        },
        {
            "name": "unit",
            "baseName": "unit",
            "type": "string",
            "format": ""
        },
        {
            "name": "location",
            "baseName": "location",
            "type": "string",
            "format": ""
        },
        {
            "name": "nativeDatum",
            "baseName": "native-datum",
            "type": "string",
            "format": ""
        },
        {
            "name": "elevation",
            "baseName": "elevation",
            "type": "number",
            "format": "double"
        },
        {
            "name": "offsets",
            "baseName": "offsets",
            "type": "Array<Offset>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return VerticalDatumInfo.attributeTypeMap;
    }

    public constructor() {
    }
}

